### ISSUE TITLE
Suggestion: Vault list page screenshot

### ISSUE THREAD

**Issue by sbrl** [codervault/codervault#15]
You've got a screenshot of a _Vault_ and a _Snippet_, but what about the list of vaults or dashboard of sorts? I assume there is one. It would help me to decide whether to install this :smiley:

**Comment by CGA1123** [comment]
@sbrl Hey!

The root page of the app `/` lists all your own vault, when you are signed in.

When you are not signed in the root `/` shows a list of public vaults on the app.

**Comment by sbrl** [comment]
@CGA1123 Ah right, cool! I might take a look at installing this then. Do you have installation instructions?

I've got an Nginx server currently. I assume that ruby has some kind of fastcgi server that I can interact with? I'm not very experienced with ruby yet :P

**Comment by CGA1123** [comment]
@sbrl This [guide](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-puma-and-nginx-on-ubuntu-14-04) might be useful for getting this set up.

**Comment by sbrl** [comment]
@CGA1123 Thanks! So CoderVault requires PostgreSQL or another database?

**Comment by CGA1123** [comment]
Currently it's using sqlite3, but you can use whatever you want, you'll just have to make sure you include the correct adapter in the Gemfile, and update the database.yml file.

**Comment by sbrl** [comment]
@CGA1123 SQLite? Awesome! I don't currently have a DB running, so I'd have to pass on installing if it required anything else.

**Comment by sbrl** [comment]
Hey there, @CGA1123! I've been busily setting up & debugging CoderVault on my server. Unfortunately, I've stumbled across a bit of a problem. Puma gets itself stuck in a restart loop and eats up a _ton_ of my cpu. I'm including a snippet of the (rather extensive) output from journalctl at the bottom of this comment. The first bit is one of the (many) restart loops it managed to perform. The lower bit is when I stopped it with `sudo systemctl stop codervault.service`.

What's gone wrong here? I haven't the faintest clue, if I'm honest :-( I'm happy to provide any of my configuration files on request, though :-)

Thanks,
--Starbeamrainbowlabs

```
codervault.service: Service hold-off time over, scheduling restart.
Jan 01 14:12:21 starbeamrainbowlabs.com systemd[1]: Stopped CoderVault HTTP Server: Puma.
Jan 01 14:12:21 starbeamrainbowlabs.com systemd[1]: Started CoderVault HTTP Server: Puma.
Jan 01 14:12:21 starbeamrainbowlabs.com puma[1466]: Puma starting in single mode...
Jan 01 14:12:21 starbeamrainbowlabs.com puma[1466]: * Version 3.6.2 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
Jan 01 14:12:21 starbeamrainbowlabs.com puma[1466]: * Min threads: 1, max threads: 4
Jan 01 14:12:21 starbeamrainbowlabs.com puma[1466]: * Environment: production
Jan 01 14:12:25 starbeamrainbowlabs.com puma[1466]: Rails Error: Unable to access log file. Please ensure that /srv/codervault/log/production.log exists and is writable (ie, ma
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]: * Activated tcp://0.0.0.0:9292
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]: * Closing unused activated socket: unix:/run/codervault/puma.sock
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]: /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/binder.rb:241:in `unlink': No such file or directory @ unlink_internal - /run/c
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/binder.rb:241:in `block in parse'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/binder.rb:234:in `each'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/binder.rb:234:in `parse'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/runner.rb:133:in `load_and_bind'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/single.rb:85:in `run'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/launcher.rb:172:in `run'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/cli.rb:74:in `run'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/bin/puma:10:in `<top (required)>'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /usr/local/bin/puma:23:in `load'
Jan 01 14:12:28 starbeamrainbowlabs.com puma[1466]:         from /usr/local/bin/puma:23:in `<main>'
Jan 01 14:12:28 starbeamrainbowlabs.com systemd[1]: codervault.service: Main process exited, code=exited, status=1/FAILURE
Jan 01 14:12:28 starbeamrainbowlabs.com systemd[1]: codervault.service: Unit entered failed state.
Jan 01 14:12:28 starbeamrainbowlabs.com systemd[1]: codervault.service: Failed with result 'exit-code'.
codervault.service: Service hold-off time over, scheduling restart.
Jan 01 14:12:28 starbeamrainbowlabs.com systemd[1]: Stopped CoderVault HTTP Server: Puma.
Jan 01 14:12:28 starbeamrainbowlabs.com systemd[1]: Started CoderVault HTTP Server: Puma.
Jan 01 14:12:29 starbeamrainbowlabs.com puma[1486]: Puma starting in single mode...
Jan 01 14:12:29 starbeamrainbowlabs.com puma[1486]: * Version 3.6.2 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
Jan 01 14:12:29 starbeamrainbowlabs.com puma[1486]: * Min threads: 1, max threads: 4
Jan 01 14:12:29 starbeamrainbowlabs.com puma[1486]: * Environment: production
Jan 01 14:12:32 starbeamrainbowlabs.com systemd[1]: Stopping CoderVault HTTP Server: Puma...
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]: ! Unable to load application: NoMethodError: undefined method `stop' for nil:NilClass
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]: /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/single.rb:16:in `stop': undefined method `stop' for nil:NilClass (NoMethodError
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/launcher.rb:146:in `stop'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/launcher.rb:382:in `block in setup_signals'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/source_annotation_extractor.rb:15:in `<top (required)>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/configuration.rb:6:in `require'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/configuration.rb:6:in `<top (required)>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/railtie.rb:18:in `require'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/railtie.rb:18:in `<class:Application>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/railtie.rb:15:in `<module:Rails>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/railtie.rb:14:in `<top (required)>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /srv/codervault/config/application.rb:11:in `require'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /srv/codervault/config/application.rb:11:in `<top (required)>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /srv/codervault/config/environment.rb:2:in `<top (required)>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from config.ru:3:in `block in <main>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `instance_eval'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `initialize'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from config.ru:in `new'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from config.ru:in `<main>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/vendor_ruby/rack/builder.rb:49:in `eval'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/vendor_ruby/rack/builder.rb:49:in `new_from_string'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/lib/ruby/vendor_ruby/rack/builder.rb:40:in `parse_file'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:315:in `load_rackup'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:243:in `app'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/runner.rb:127:in `load_and_bind'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/single.rb:85:in `run'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/launcher.rb:172:in `run'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/lib/puma/cli.rb:74:in `run'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /var/lib/gems/2.3.0/gems/puma-3.6.2/bin/puma:10:in `<top (required)>'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/local/bin/puma:23:in `load'
Jan 01 14:12:32 starbeamrainbowlabs.com puma[1486]:         from /usr/local/bin/puma:23:in `<main>'
Jan 01 14:12:32 starbeamrainbowlabs.com systemd[1]: codervault.service: Main process exited, code=exited, status=1/FAILURE
Jan 01 14:12:32 starbeamrainbowlabs.com systemd[1]: Stopped CoderVault HTTP Server: Puma.
Jan 01 14:12:32 starbeamrainbowlabs.com systemd[1]: codervault.service: Unit entered failed state.
Jan 01 14:12:32 starbeamrainbowlabs.com systemd[1]: codervault.service: Failed with result 'exit-code'.
```

**Comment by SaphireLattice** [comment]
Screenshots are missing/unavailable, probably due to hitting Dropbox limit or just being removed.

Also hm, don't think the discussion above is quite on-topic for the issue's actual title.
